# features/management/commands/train_models.py

from pathlib import Path

from django.core.management.base import BaseCommand

from features.ml.training import (
    train_long_model_with_holdout,
    train_short_model_with_holdout,
    FeatureMode,
)


class Command(BaseCommand):
    help = "Train long/short ML models from the feature CSV."

    def add_arguments(self, parser):
        parser.add_argument(
            "--features_csv",
            type=str,
            default="features_14d_5pct.csv",
            help="Path to the features CSV generated by build_features.",
        )
        parser.add_argument(
            "--out_dir",
            type=str,
            default="models",
            help="Directory to save trained models.",
        )
        parser.add_argument(
            "--no_short",
            action="store_true",
            help="Only train the long model, skip the short model.",
        )
        parser.add_argument(
            "--mode",
            type=str,
            choices=["pure", "hybrid"],
            default="hybrid",
            help="Feature mode: 'pure' excludes all regime signals, 'hybrid' keeps regimes but excludes trading signals.",
        )
        parser.add_argument(
            "--lag",
            type=int,
            default=0,
            help="Decision lag in days (shift features to avoid lookahead). 0=no lag, 1=trade next day.",
        )

    def handle(self, *args, **options):
        csv_path = Path(options["features_csv"])
        out_dir = Path(options["out_dir"])
        mode = FeatureMode(options["mode"])
        decision_lag = options["lag"]

        if not csv_path.exists():
            self.stderr.write(self.style.ERROR(f"Features CSV not found: {csv_path}"))
            return

        out_dir.mkdir(parents=True, exist_ok=True)

        long_model_path = out_dir / "long_model.joblib"
        short_model_path = out_dir / "short_model.joblib"

        # Train long model
        self.stdout.write(self.style.MIGRATE_HEADING("Training LONG model..."))
        train_long_model_with_holdout(csv_path, long_model_path, mode=mode, decision_lag=decision_lag)

        if not options["no_short"]:
            self.stdout.write(self.style.MIGRATE_HEADING("Training SHORT model..."))
            train_short_model_with_holdout(csv_path, short_model_path, mode=mode, decision_lag=decision_lag)

        self.stdout.write(self.style.SUCCESS("Model training completed."))
