# features/management/commands/train_models.py

from pathlib import Path

from django.core.management.base import BaseCommand

from features.ml.training import (
    train_long_model_with_holdout,
    train_short_model_with_holdout,
)



class Command(BaseCommand):
    help = "Train long/short ML models from the feature CSV."

    def add_arguments(self, parser):
        parser.add_argument(
            "--features_csv",
            type=str,
            default="features_14d_5pct.csv",
            help="Path to the features CSV generated by build_features.",
        )
        parser.add_argument(
            "--out_dir",
            type=str,
            default="models",
            help="Directory to save trained models.",
        )
        parser.add_argument(
            "--no_short",
            action="store_true",
            help="Only train the long model, skip the short model.",
        )

    def handle(self, *args, **options):
        csv_path = Path(options["features_csv"])
        out_dir = Path(options["out_dir"])

        if not csv_path.exists():
            self.stderr.write(self.style.ERROR(f"Features CSV not found: {csv_path}"))
            return

        out_dir.mkdir(parents=True, exist_ok=True)

        long_model_path = out_dir / "long_model.joblib"
        short_model_path = out_dir / "short_model.joblib"

        # Train long model
        self.stdout.write(self.style.MIGRATE_HEADING("Training LONG model..."))
        train_long_model_with_holdout(csv_path, long_model_path)

        if not options["no_short"]:
            self.stdout.write(self.style.MIGRATE_HEADING("Training SHORT model..."))
            train_short_model_with_holdout(csv_path, short_model_path)

        self.stdout.write(self.style.SUCCESS("Model training completed."))
