# Generated by Django 4.2.23 on 2025-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('mdia', models.FloatField(blank=True, null=True)),
                ('mvrv_long_short_diff_usd', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_1d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_7d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_30d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_60d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_90d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_180d', models.FloatField(blank=True, null=True)),
                ('mvrv_usd_365d', models.FloatField(blank=True, null=True)),
                ('btc_holders_1_10', models.FloatField(blank=True, null=True)),
                ('btc_holders_10_100', models.FloatField(blank=True, null=True)),
                ('btc_holders_100_1k', models.FloatField(blank=True, null=True)),
                ('btc_holders_1k_10k', models.FloatField(blank=True, null=True)),
                ('sentiment_weighted_total', models.FloatField(blank=True, null=True)),
                ('btc_open', models.FloatField(blank=True, null=True)),
                ('btc_high', models.FloatField(blank=True, null=True)),
                ('btc_low', models.FloatField(blank=True, null=True)),
                ('btc_close', models.FloatField(blank=True, null=True)),
                ('btc_price_normalised', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raw_daily_data',
                'ordering': ['date'],
            },
        ),
    ]
