# Generated by Django 4.2.23 on 2025-12-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdailydata',
            name='btc_close',
        ),
    ]
