# Generated by Django 4.2.23 on 2025-12-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0002_remove_rawdailydata_btc_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdailydata',
            name='btc_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
