# Generated by Django 4.2.23 on 2025-12-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0003_rawdailydata_btc_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdailydata',
            old_name='btc_price_normalised',
            new_name='btc_price_mean',
        ),
    ]
