# Generated by Django 4.2.23 on 2026-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0004_rename_btc_price_normalised_rawdailydata_btc_price_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdailydata',
            name='exchange_flow_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
