# Generated by Django 4.2.23 on 2026-04-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0005_rawdailydata_exchange_flow_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('underlying', models.CharField(default='BTC', max_length=16)),
                ('expiry', models.DateTimeField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option_type', models.CharField(max_length=4)),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('mid_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('iv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('bid_size', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ask_size', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('dte', models.FloatField(blank=True, null=True)),
                ('moneyness', models.FloatField(blank=True, null=True)),
                ('spread_pct', models.FloatField(blank=True, null=True)),
                ('exchange', models.CharField(default='bybit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'option_snapshot',
            },
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=64, unique=True)),
                ('signal_type', models.CharField(db_index=True, max_length=32)),
                ('direction', models.CharField(max_length=8)),
                ('entry_timestamp', models.DateTimeField(db_index=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_spot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_iv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('symbol', models.CharField(max_length=64)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notional', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('exit_spot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exit_iv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('max_favorable_excursion', models.FloatField(blank=True, null=True)),
                ('max_adverse_excursion', models.FloatField(blank=True, null=True)),
                ('iv_change', models.FloatField(blank=True, null=True)),
                ('spot_change_pct', models.FloatField(blank=True, null=True)),
                ('is_paper', models.BooleanField(default=True)),
                ('exchange', models.CharField(default='bybit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_trades', to='datafeed.optionsnapshot')),
                ('exit_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_trades', to='datafeed.optionsnapshot')),
            ],
            options={
                'db_table': 'option_trade',
            },
        ),
        migrations.AddIndex(
            model_name='optionsnapshot',
            index=models.Index(fields=['timestamp', 'symbol'], name='option_snap_timesta_7737c0_idx'),
        ),
        migrations.AddIndex(
            model_name='optionsnapshot',
            index=models.Index(fields=['underlying', 'expiry', 'strike'], name='option_snap_underly_2ecca6_idx'),
        ),
        migrations.AddIndex(
            model_name='optionsnapshot',
            index=models.Index(fields=['timestamp', 'underlying', 'dte'], name='option_snap_timesta_28f25d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionsnapshot',
            unique_together={('timestamp', 'symbol', 'exchange')},
        ),
        migrations.AddIndex(
            model_name='optiontrade',
            index=models.Index(fields=['entry_timestamp'], name='option_trad_entry_t_921389_idx'),
        ),
        migrations.AddIndex(
            model_name='optiontrade',
            index=models.Index(fields=['signal_type', 'entry_timestamp'], name='option_trad_signal__55874c_idx'),
        ),
    ]
