# Generated by Django 4.2.23 on 2026-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0006_add_option_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='leg_role',
            field=models.CharField(blank=True, default='', help_text="Role in spread: 'short' or 'long' (empty for single-leg trades)", max_length=10),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='risk_tier',
            field=models.CharField(blank=True, default='', help_text="Risk tier chosen by human: 'low', 'medium', 'high' (income spreads only)", max_length=10),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='spread_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups legs of the same spread. Both legs share this ID.', max_length=64, null=True),
        ),
    ]
