# Generated by Django 4.2.23 on 2025-12-27 11:14
# Fixed: Use SeparateDatabaseAndState to register model in signals app state
# WITHOUT creating the table (it already exists from features app)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0003_delete_dailysignal'),  # Must run after features drops ownership
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DailySignal',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField(db_index=True, unique=True)),
                        ('p_long', models.FloatField(help_text='ML probability for long position')),
                        ('p_short', models.FloatField(help_text='ML probability for short position')),
                        ('signal_option_call', models.IntegerField(help_text='Call signal (0/1)')),
                        ('signal_option_put', models.IntegerField(help_text='Put signal (0/1)')),
                        ('fusion_state', models.CharField(help_text='Market state from fusion engine (e.g., STRONG_BULLISH)', max_length=50)),
                        ('fusion_confidence', models.CharField(help_text='Confidence level (HIGH/MEDIUM/LOW)', max_length=20)),
                        ('fusion_score', models.IntegerField(help_text='Numeric fusion score')),
                        ('overlay_reason', models.TextField(blank=True, default='', help_text='Explanation from overlay logic')),
                        ('size_multiplier', models.FloatField(default=1.0, help_text='Position size multiplier from overlay')),
                        ('dte_multiplier', models.FloatField(default=1.0, help_text='DTE adjustment multiplier')),
                        ('tactical_put_active', models.BooleanField(default=False, help_text='Whether tactical put was triggered')),
                        ('tactical_put_strategy', models.CharField(blank=True, default='', help_text='Strategy type if tactical put active', max_length=50)),
                        ('tactical_put_size', models.FloatField(default=0.0, help_text='Tactical put sizing')),
                        ('trade_decision', models.CharField(help_text='Final trade decision (CALL/PUT/TACTICAL_PUT/NO_TRADE)', max_length=30)),
                        ('trade_notes', models.TextField(blank=True, default='', help_text='Additional notes about the trade decision')),
                        ('no_trade_reasons', models.JSONField(blank=True, default=list, help_text='List of reason codes for NO_TRADE (e.g., FUSION_STATE_NO_TRADE, CONFIDENCE_TOO_LOW)')),
                        ('decision_trace', models.JSONField(blank=True, default=list, help_text='Step-by-step decision gates (fusion → overlay → ml → final)')),
                        ('effective_size', models.FloatField(default=0.0, help_text='Final computed position size (0 on NO_TRADE)')),
                        ('effective_dte_range', models.CharField(blank=True, default='', help_text='Final DTE range to use (empty on NO_TRADE)', max_length=30)),
                        ('option_structures', models.CharField(blank=True, default='', help_text='Recommended option structures (e.g., long_call, call_spread)', max_length=200)),
                        ('strike_guidance', models.CharField(blank=True, default='', help_text='Strike selection guidance (e.g., atm, slight_otm)', max_length=30)),
                        ('dte_range', models.CharField(blank=True, default='', help_text='Days to expiration range (e.g., 45-90d)', max_length=30)),
                        ('strategy_rationale', models.TextField(blank=True, default='', help_text='Human-readable strategy rationale')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Daily Signal',
                        'verbose_name_plural': 'Daily Signals',
                        'db_table': 'daily_signal',
                        'ordering': ['-date'],
                    },
                ),
            ],
            database_operations=[],  # Table already exists from features app
        ),
    ]
