# Generated by Django 4.2.23 on 2025-12-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysignal',
            name='effective_dte_range',
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='decision_version',
            field=models.CharField(blank=True, default='', help_text='Version of decision logic (e.g., 2025-12-28.1)', max_length=30),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='model_versions',
            field=models.JSONField(blank=True, default=dict, help_text="Model versions used: {long: 'filename', short: 'filename'}"),
        ),
        # Note: score_components already exists from previous migration, just format of data changed
    ]
