# Generated by Django 4.2.23 on 2026-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_remove_dailysignal_effective_dte_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='score_components',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown of score: {mdia: {score: 2, label: 'strong_inflow'}, ...}"),
        ),
    ]
