# Generated by Django 4.2.23 on 2026-02-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_dailysignal_score_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='short_source',
            field=models.CharField(blank=True, default='', help_text='Source of short signal: rule or score (empty for non-short states)', max_length=10),
        ),
    ]
