# Generated by Django 4.2.23 on 2026-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_dailysignal_short_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='stop_loss',
            field=models.CharField(blank=True, default='', help_text='Stop loss guidance (e.g., 4.0% stop | scale to 25% on day 5 | hard cut day 6)', max_length=200),
        ),
    ]
