# Generated by Django 4.2.23 on 2026-02-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_add_stop_loss'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='dailysignal',
                    name='effective_dte_range',
                ),
            ],
            database_operations=[],
        ),
    ]
