# Generated by Django 4.2.23 on 2026-03-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_remove_dailysignal_effective_dte_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='max_hold_days',
            field=models.IntegerField(blank=True, help_text='Hard time stop: close all remaining on this day', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='scale_down_day',
            field=models.IntegerField(blank=True, help_text='Day to reduce position to 25% (time-based scale-down)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='spread_width_pct',
            field=models.FloatField(blank=True, help_text='Spread width as decimal (e.g., 0.10 = 10% width)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='stop_loss_pct',
            field=models.FloatField(blank=True, help_text='Stop loss as decimal (e.g., 0.04 = 4% adverse move triggers exit)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='take_profit_pct',
            field=models.FloatField(blank=True, help_text='Take profit target as decimal (e.g., 0.70 = 70% of max spread value)', null=True),
        ),
    ]
