# Generated by Django 4.2.23 on 2026-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_add_condor_gate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='condor_cost_basis',
            field=models.FloatField(blank=True, help_text='MVRV-60d implied cost basis (spot / mvrv_60d)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='condor_short_call',
            field=models.FloatField(blank=True, help_text='Short call strike = max(spot*1.10, CB*1.12)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='condor_short_put',
            field=models.FloatField(blank=True, help_text='Short put strike = min(spot*0.90, CB*0.92)', null=True),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='condor_strike_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Strike computation metadata: sources, distances, mvrv_60d'),
        ),
    ]
