# Generated by Django 4.2.23 on 2026-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_dailysignal_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='income_spread_eligible',
            field=models.BooleanField(default=False, help_text='Whether income gate passed (score >= threshold, no vetoes, chain valid)'),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='income_spread_score',
            field=models.FloatField(default=0.0, help_text='Income gate score (0-100)'),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='income_spread_setups',
            field=models.JSONField(blank=True, default=list, help_text='List of risk-tiered spread setups [{risk_tier, short_strike, long_strike, credit, spread_width, dte, max_loss, short_delta, credit_width_pct, otm_pct, risk_reward}]'),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='income_spread_veto_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Veto reasons blocking income spread entry'),
        ),
    ]
