# Generated by Django 4.2.23 on 2026-06-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_income_spread_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysignal',
            name='strike_guidance',
            field=models.CharField(blank=True, default='', help_text='Strike selection guidance (e.g., atm, slight_otm)', max_length=200),
        ),
    ]
