# Generated by Django 4.2.23 on 2026-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_alter_dailysignal_strike_guidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbitWheelSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(db_index=True)),
                ('trade_decision', models.CharField(help_text='BULL_PUT_SPREAD or BEAR_CALL_SPREAD', max_length=30)),
                ('side', models.CharField(help_text='put or call', max_length=4)),
                ('position', models.CharField(help_text='cash_secured_put or covered_call', max_length=20)),
                ('spot_price', models.FloatField(help_text='IBIT spot used for selection')),
                ('dte_mode', models.CharField(default='income', max_length=10)),
                ('legs', models.JSONField(default=list)),
                ('selection_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IBIT Wheel Setup',
                'verbose_name_plural': 'IBIT Wheel Setups',
                'db_table': 'ibit_wheel_setup',
                'ordering': ['-signal_date', 'trade_decision'],
            },
        ),
        migrations.AddConstraint(
            model_name='ibitwheelsetup',
            constraint=models.UniqueConstraint(fields=('signal_date', 'trade_decision'), name='unique_ibit_wheel_per_signal'),
        ),
    ]
