# Generated by Django 4.2.23 on 2025-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('p_long', models.FloatField(help_text='ML probability for long position')),
                ('p_short', models.FloatField(help_text='ML probability for short position')),
                ('signal_option_call', models.IntegerField(help_text='Call signal (0/1)')),
                ('signal_option_put', models.IntegerField(help_text='Put signal (0/1)')),
                ('fusion_state', models.CharField(help_text='Market state from fusion engine (e.g., STRONG_BULLISH)', max_length=50)),
                ('fusion_confidence', models.CharField(help_text='Confidence level (HIGH/MEDIUM/LOW)', max_length=20)),
                ('fusion_score', models.IntegerField(help_text='Numeric fusion score')),
                ('overlay_reason', models.TextField(blank=True, default='', help_text='Explanation from overlay logic')),
                ('size_multiplier', models.FloatField(default=1.0, help_text='Position size multiplier from overlay')),
                ('dte_multiplier', models.FloatField(default=1.0, help_text='DTE adjustment multiplier')),
                ('tactical_put_active', models.BooleanField(default=False, help_text='Whether tactical put was triggered')),
                ('tactical_put_strategy', models.CharField(blank=True, default='', help_text='Strategy type if tactical put active', max_length=50)),
                ('tactical_put_size', models.FloatField(default=0.0, help_text='Tactical put sizing')),
                ('trade_decision', models.CharField(help_text='Final trade decision (CALL/PUT/TACTICAL_PUT/NO_TRADE)', max_length=30)),
                ('trade_notes', models.TextField(blank=True, default='', help_text='Additional notes about the trade decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Signal',
                'verbose_name_plural': 'Daily Signals',
                'db_table': 'daily_signal',
                'ordering': ['-date'],
            },
        ),
    ]
