# Generated by Django 4.2.23 on 2025-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysignal',
            name='dte_range',
            field=models.CharField(blank=True, default='', help_text='Days to expiration range (e.g., 45-90d)', max_length=30),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='option_structures',
            field=models.CharField(blank=True, default='', help_text='Recommended option structures (e.g., long_call, call_spread)', max_length=200),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='strategy_rationale',
            field=models.TextField(blank=True, default='', help_text='Human-readable strategy rationale'),
        ),
        migrations.AddField(
            model_name='dailysignal',
            name='strike_guidance',
            field=models.CharField(blank=True, default='', help_text='Strike selection guidance (e.g., atm, slight_otm)', max_length=30),
        ),
    ]
