# Generated by Django 4.2.23 on 2026-02-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_add_option_strategy_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySignal',
        ),
    ]
