# Generated by Django 4.2.23 on 2026-02-09 05:03
# Fixed: Use SeparateDatabaseAndState to remove model from features app state
# WITHOUT deleting the actual table (ownership moves to signals app)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_add_option_strategy_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DailySignal',
                ),
            ],
            database_operations=[],  # Don't touch the actual table
        ),
    ]
