# Generated by Django 4.2.23 on 2026-03-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_position_executionevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executionevent',
            new_name='execution_e_event_t_71e4ce_idx',
            old_name='execution_e_event_t_789abc_idx',
        ),
        migrations.RenameIndex(
            model_name='executionintent',
            new_name='execution_i_signal__a70b0d_idx',
            old_name='execution_i_signal__abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='executionintent',
            new_name='execution_i_account_f86b75_idx',
            old_name='execution_i_account_def456_idx',
        ),
        migrations.AlterField(
            model_name='exchangeaccount',
            name='api_key_env',
            field=models.CharField(help_text='Environment variable name for API key (e.g., BYBIT_API_KEY)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['exchange_order_id'], name='execution_o_exchang_bac019_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='execution_o_status_370cab_idx'),
        ),
    ]
