# Generated by Django 4.2.23 on 2026-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_rename_execution_e_event_t_789abc_idx_execution_e_event_t_71e4ce_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionintent',
            name='spread_long_symbol',
            field=models.CharField(blank=True, help_text='Long leg symbol for spreads', max_length=50),
        ),
        migrations.AddField(
            model_name='executionintent',
            name='spread_short_symbol',
            field=models.CharField(blank=True, help_text='Short leg symbol for spreads', max_length=50),
        ),
    ]
