# Generated by Django 4.2.23 on 2026-03-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_add_spread_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionintent',
            name='exit_method',
            field=models.CharField(blank=True, help_text='native (exchange SL/TP) or polling (manage_exits)', max_length=20),
        ),
        migrations.AddField(
            model_name='executionintent',
            name='protected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionintent',
            name='stop_loss_order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='executionintent',
            name='take_profit_order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='executionintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('risk_check', 'Risk Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('entry_submitted', 'Entry Submitted'), ('entry_filled', 'Entry Filled'), ('exits_placed', 'Exits Placed'), ('protected', 'Protected'), ('unprotected', 'Unprotected'), ('exit_triggered', 'Exit Triggered'), ('closed', 'Closed'), ('partial', 'Partially Filled'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('executing', 'Executing'), ('filled', 'Filled')], default='pending', max_length=20),
        ),
    ]
