# Generated by Django 4.2.23 on 2026-05-24 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_dailysignal_is_active'),
        ('execution', '0007_v1_protection_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSetupSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setup_data', models.JSONField(help_text='Full trade setup snapshot')),
                ('signal_date', models.DateField(db_index=True)),
                ('signal_type', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=10)),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contracts', models.IntegerField()),
                ('validation_passed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_setups', to='signals.dailysignal')),
            ],
            options={
                'db_table': 'trade_setup_snapshot',
                'ordering': ['-signal_date'],
                'indexes': [models.Index(fields=['signal_date', 'signal_type'], name='trade_setup_signal__474856_idx')],
            },
        ),
    ]
