# Generated by Django 4.2.23 on 2026-05-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_dailysignal_is_active'),
        ('execution', '0008_add_trade_setup_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradesetupsnapshot',
            name='signal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_setup', to='signals.dailysignal'),
        ),
    ]
