# Generated by Django 4.2.23 on 2026-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_trade_setup_snapshot_unique_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeaccount',
            name='api_key_env',
            field=models.CharField(help_text='Environment variable name for API key (e.g., DERIBIT_API_KEY)', max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangeaccount',
            name='exchange',
            field=models.CharField(choices=[('deribit', 'Deribit')], max_length=20),
        ),
    ]
