# Generated by Django 4.2.23 on 2026-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(db_index=True)),
                ('trade_decision', models.CharField(max_length=30)),
                ('selection_hash', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wheel Publication',
                'verbose_name_plural': 'Wheel Publications',
                'db_table': 'wheel_publication',
            },
        ),
        migrations.AddConstraint(
            model_name='wheelpublication',
            constraint=models.UniqueConstraint(fields=('signal_date', 'trade_decision'), name='unique_wheel_publication_per_signal'),
        ),
    ]
