# Generated by Django 4.2.23 on 2026-08-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WheelPublication',
        ),
    ]
